version: '3.7'

services:
  postgres-account:
    image: 'postgres:11.1'
    networks:
      - net
    ports:
      - 5432:5432
    environment:
      LC_ALL: 'C.UTF-8'
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: postgres
      POSTGRES_DB: account-develop
      PGDATA: /var/lib/postgresql/data
    restart: unless-stopped

networks:
  net:
    driver: bridge
