--- # cloud # ---
server:
  port: 8080

spring:
  profiles: cloud
  data:
    mongodb:
      host: mongodb
      database: account-cloud

security:
  token:
    secret-key: "KuHLb3w7YE2WF@o39ds3hDSdsdfdKhs5kdsdsKH@fD"
    expires-in: 3600000
    token-type: "bearer"

--- # staging # ---
server:
  port: 9001

spring:
  profiles: staging
  data:
    mongodb:
      database: account-staging

security:
  token:
    secret-key: "KuHLb3w7YE2WF@o39ds3hDSdsdfdKhs5kdsdsKH@fD"
    expires-in: 3600000
    token-type: "bearer"

--- # develop # ---
server:
  port: 9001

spring:
  profiles:
    active: develop
  data:
    mongodb:
      database: account-develop

security:
  token:
    secret-key: "KuHLb3w7YE2WF@o39ds3hDSdsdfdKhs5kdsdsKH@fD"
    expires-in: 3600000
    token-type: "bearer"
